server:
  port: 8501

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console

spring:
  application:
    name: boot-redis
  redis:
    host: 192.168.159.111
    port: 6379
    database: 0
    password: redis123
    timeout: 10000
    lettuce:
      pool:
        max-active: 50
        min-idle: 5
        max-idle: 50
        max-wait: 5000

com:
  felix:
    mq:
      brokers: 192.168.159.111:6379
      ak:
      sk:
      producers:
        - name: orderPlaceProducer
          group: order_01_group
          topic: order_topic
          tag: place
      consumers:
        - name: orderConsumer
          group: order_01_group
          topic: order_topic
          tag: place,pay
