server:
  port: 8505

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console

spring:
  application:
    name: boot-redis-origin

com:
  felix:
    mq:
      brokers: redis://192.168.159.111:6379
      ak: redis123
      producers:
        - name: orderPlaceProducer
          topic: order_topic
      consumers:
        - name: orderConsumer
          topic: order_topic
