server:
  port: 8504

logging:
  level:
    root: info
    com.felix: debug
  customize:
    appender: console

spring:
  application:
    name: boot-kafka-origin

com:
  felix:
    mq:
      brokers: 192.168.197.101:9876
      ak:
      sk:
      producers:
        - name: orderPlaceProducer
          group: order_01_group
          topic: order_topic
          tag: place
      consumers:
        - name: orderConsumer
          group: order_01_group
          topic: order_topic
          tag: place,pay
